### PR TITLE
initial thanos query-frontend chart

### PR DESCRIPTION
**Pull request by spencergilbert**
#### What this PR does / why we need it:

Initial query-frontend chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by spencergilbert** [comment]
The changes look good to me - I'm going to get it deployed in one of our clusters

**Comment by spencergilbert** [comment]
@obiesmans - all looks good and is running fine after I updated. I think the first order of business is going to be prettifying and improving the readme's but functionally I think we're in a good spot.

On the query chart I added support for initContainers and additional containers to run in the pod for people who might manually configure proxy sidecars and the like. Should we add that here as well before merging?

**Comment by obiesmans** [comment]
@spencergilbert : Thanks for your review. I've added `initContainers` functionnality. I agree with you that the Readme could be more refined.

**Review by obiesmans — APPROVED** [review]

**Comment by spencergilbert** [comment]
LGTM - are we good with merging this then?

**Pull request merged**
